dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - make install

script:
  - make test/ci
  - make e2e/ci

deploy:
  provider: script
  skip_cleanup: true
  script:
    - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && make deploy/angular/ci'
  on:
    branch: master
